<?php

namespace BctBundle\Repository;

/**
 * Tcc_sous_catRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Tcc_sous_catRepository extends \Doctrine\ORM\EntityRepository
{
    public function findByTcc($tccs)
    {
        $qb = $this->createQueryBuilder('u')
            ->select('u')
            ->where('u.Tcc_principale = :tccs')
            ->orderBy('u.id')
            ->setParameter('tccs',$tccs);
         return $qb->getQuery()->getResult();
    }

}
