<?php

namespace BctBundle\Repository;

/**
 * Tcc_principaleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Tcc_principaleRepository extends \Doctrine\ORM\EntityRepository
{
   
}
